# Generated by Django 5.2.1 on 2025-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EuroCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField(verbose_name="Цена в рублях")),
                (
                    "date",
                    models.DateField(verbose_name="Дата, на которую актуален курс"),
                ),
            ],
        ),
    ]
