# Generated by Django 5.2.1 on 2025-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eurocourse",
            options={"verbose_name": "Курс евро", "verbose_name_plural": "Курсы евро"},
        ),
        migrations.AlterField(
            model_name="eurocourse",
            name="dt_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="eurocourse",
            name="dt_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
