# Generated by Django 5.2.1 on 2025-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0002_alter_eurocourse_options_alter_eurocourse_dt_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EuroForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "dt_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "date",
                    models.DateField(verbose_name="Дата, на которую актуален прогноз"),
                ),
                ("forecast", models.CharField(max_length=255, verbose_name="Прогноз")),
            ],
            options={
                "verbose_name": "Прогноз евро",
                "verbose_name_plural": "Прогнозы евро",
            },
        ),
    ]
